### ISSUE TITLE
Exclude unsupported VM size

### ISSUE THREAD

**Issue by galiacheng** [WASdev/azure.liberty.aks#114]
AKS does not support the following VM sizes:

- https://aka.ms/aks/restricted-skus.
- B-series node sizes cannot be scheduled for agent pool.

![image](https://github.com/WASdev/azure.liberty.aks/assets/59823457/db628fd4-af91-4977-a2b1-7513b281b6e1)

We should exclude them from the UI definition.

**Comment by majguo** [comment]
Reference PR: https://github.com/oracle/weblogic-azure/pull/318

**Comment by majguo** [comment]
The other enhancements not related to this issue but required:
* https://github.com/oracle/weblogic-azure/pull/318
* https://github.com/oracle/weblogic-azure/pull/319
