### ISSUE TITLE
Default image names should work.

### ISSUE THREAD

**Issue by m-reza-rahman** [WASdev/azure.liberty.aks#13]
Simply specifying "websphere-liberty" as image name should work. Instead, it seems you have specify the full image path (e.g., "docker.io/ibmcom/websphere-liberty:latest").

Most people will expect an experience similar to "docker pull websphere-liberty" and would be confused as to why the deployment is failing.

Also, this seems to work for the ARO offer.

**Comment by majguo** [comment]
The root cause is that `az acr import` requires a full image path. As `websphere-liberty` is an Docker Official Image, it's equivalent to the full path `docker.io/library/websphere-liberty` based on my testing:
```
docker pull websphere-liberty

Using default tag: latest
latest: Pulling from library/websphere-liberty
Digest: sha256:fd9da842ce7124e2bf6254e4d4fb62b521cae28c83f2805c91cbc8ef42516946
Status: Image is up to date for websphere-liberty:latest
docker.io/library/websphere-liberty:latest
```

So the solution to fix the issue will be concatenating `docker.io/library/` to the beginning of the user-input image path if it's a short one.

**Comment by m-reza-rahman** [comment]
This sounds good. However, can you please experiment a bit with docker pull to see what it does? That’s the behavior I think we should try to emulate. Also, should we file an issue on acr import?

**Comment by majguo** [comment]
I have already experimented with `docker pull websphere-liberty`, finally `docker.io/library/websphere-liberty` is pulled:
```
docker pull websphere-liberty

Using default tag: latest
latest: Pulling from library/websphere-liberty
Digest: sha256:fd9da842ce7124e2bf6254e4d4fb62b521cae28c83f2805c91cbc8ef42516946
Status: Image is up to date for websphere-liberty:latest
docker.io/library/websphere-liberty:latest
```
Regarding to `az acr import`, I think imposing a full qualified path is reasonable, as it doesn't know what is the correct image registry, maybe it's `docker.io`, or something else that is anonymous accessible.

**Comment by m-reza-rahman** [comment]
Just for curiosity, have you tried J9, JDK, Open Liberty, WildFly, Tomcat, etc? Does the same thing happen? I am just curious whether the default is hard coded or pulled from some kind of metadata somewhere.

**Comment by majguo** [comment]
Same thing happen:
* [`tomcat` docker official image](https://hub.docker.com/_/tomcat)
```
docker pull tomcat
Using default tag: latest
latest: Pulling from library/tomcat
5e0b432e8ba9: Pull complete
a84cfd68b5ce: Pull complete
e8b8f2315954: Pull complete
0598fa43a7e7: Pull complete
e0d35e3be804: Pull complete
8fc448a0c88b: Pull complete
dbdff6e5955b: Pull complete
5daf3771e3d8: Pull complete
b7111881cc7c: Pull complete
0721390e30ba: Pull complete
Digest: sha256:2fa718d2e1651e9fb75e187978ac5ee0fe937f19ee92968154fae4f00a9763ff
Status: Downloaded newer image for tomcat:latest
docker.io/library/tomcat:latest
``` 
* [`openjdk` docker official image](https://hub.docker.com/_/openjdk)
```
docker pull openjdk
Using default tag: latest
latest: Pulling from library/openjdk
28587b6e6475: Pull complete
b1655352c888: Pull complete
1f9646f00e96: Pull complete
Digest: sha256:0e5ae79482731eef1526afb4e3a42e62b38142681c5752a944ff4236da979648
Status: Downloaded newer image for openjdk:latest
docker.io/library/openjdk:latest
```
* [`adoptopenjdk` docker official image](https://hub.docker.com/_/adoptopenjdk)
```
docker pull adoptopenjdk
Using default tag: latest
latest: Pulling from library/adoptopenjdk
f3ef4ff62e0d: Pull complete
706b9b9c1c44: Pull complete
66893017ee66: Pull complete
Digest: sha256:3f2982d13b40d8c6d56a3a736c4f6c51a3c99688c2b434a27ed5d1b5f3fbedfb
Status: Downloaded newer image for adoptopenjdk:latest
docker.io/library/adoptopenjdk:latest
```
* Official docker image for `openliberty` is not found from DockerHub
* Official docker image for `WildFly` is not found from DockerHub

**Comment by m-reza-rahman** [comment]
Thanks for checking! Let’s move forward?

**Comment by edburns** [comment]
Please put a prominent info box on the **Configure application** blade that reminds the user they must ensure the image they are specifying is "anonymously pullable".

**Comment by edburns** [comment]
See https://github.com/WASdev/azure.liberty.aro/issues/47#issuecomment-986425704

**Comment by majguo** [comment]
> Thanks for checking! Let’s move forward?

@m-reza-rahman Yes, it's on-going now. See pull request [Docker image path fallback](https://github.com/WASdev/azure.liberty.aks/pull/20)

**Comment by edburns** [comment]
Consider having an example text like in Azure Container Instances: 

![image](https://user-images.githubusercontent.com/75821/144787023-80d95176-8515-40a1-8bfa-8d6613d69bdd.png)
