### ISSUE TITLE
Fix warning "The apiVersion 2021-09-30-preview was not found for the resource type: Microsoft.ManagedIdentity/userAssignedIdentities"

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aks#61]
The following warning is observed from the log of [integration-test pipeline](https://github.com/majguo/azure.liberty.aks/actions/runs/2996852737):

```
The apiVersion 2021-09-30-preview was not found for the resource type: Microsoft.ManagedIdentity/userAssignedIdentitiess
```

**Comment by venunathb** [comment]
[ARM-Package workflow](https://github.com/WASdev/azure.liberty.aks/actions/runs/7563622883) successfully updated the artificats for azure-aks 1.3.0
