### ISSUE TITLE
Create GitHub Action secrets needed to run new added pipeline `integration-test`

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aks#63]
Hello @git4rk The following GitHub Action secrets are needed to run new added pipeline `integration-test`

* AZURE_CREDENTIALS
  1. Use the same value of secret `AZURE_CREDENTIALS` defined in [WASdev/azure.websphere-traditional.singleserver](https://github.com/WASdev/azure.websphere-traditional.singleserver) or create a new one by following [this](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/58#issuecomment-839974811).
  1. Grant `User Access Administrator` role in the subscription to the service principal you specified in the previous step:
      ```
      export SUBSCRIPTION_ID=<sub-id>
      export SP_NAME=<service-principal-display-name>

      APP_ID=$(az ad sp list --display-name $SP_NAME | jq '.[0]' | jq -r '.appId')
      az role assignment create --assignee $APP_ID --role "User Access Administrator" --scope /subscriptions/${SUBSCRIPTION_ID}
      ```
  1. Verify that both `Contributor` and `User Access Administrator` roles in the subscription are granted to the service principal:
      ```
      az role assignment list --assignee $APP_ID
      ```
      You should see the similar output:
      ```
      [
        {
          ...
          "roleDefinitionName": "Contributor",
          ...
        },
        {
          ...
          "roleDefinitionName": "User Access Administrator",
          ...
        }
     ]
      ```

* USER_NAME
  * Use `WASdev`
* IS_INTERNAL_SUBSCRIPTION
  * Use `false`
* MSTEAMS_WEBHOOK
  * Use the same value of secret `MSTEAMS_WEBHOOK` defined in [WASdev/azure.websphere-traditional.singleserver](https://github.com/WASdev/azure.websphere-traditional.singleserver)

Reference the following issue for more information:
* WASdev/azure.websphere-traditional.singleserver/issues/44

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue once you add the required secrets by following steps above.

**Comment by git4rk** [comment]
Added these secrets
<img width="849" alt="image" src="https://user-images.githubusercontent.com/24283162/189261847-cdf18896-de35-40c3-9c6c-3843dad7dae4.png">

% az role assignment list --assignee $APP_ID
```
[
  {
    "canDelegate": null,
    "condition": null,
    "conditionVersion": null,
    "description": null,
    "id": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/providers/Microsoft.Authorization/roleAssignments/9da83844-9c73-42d9-a27c-447fb8a14ed8",
    "name": "9da83844-9c73-42d9-a27c-447fb8a14ed8",
    "principalId": "972d3c01-4b24-4fd2-9aeb-7c0cea2262fa",
    "principalName": "http://20210512_IBM_SP",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
    "roleDefinitionName": "Contributor",
    "scope": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3",
    "type": "Microsoft.Authorization/roleAssignments"
  },
  {
    "canDelegate": null,
    "condition": null,
    "conditionVersion": null,
    "description": null,
    "id": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/providers/Microsoft.Authorization/roleAssignments/7e4575ae-9194-4e05-a8cc-e2d7604735de",
    "name": "7e4575ae-9194-4e05-a8cc-e2d7604735de",
    "principalId": "972d3c01-4b24-4fd2-9aeb-7c0cea2262fa",
    "principalName": "http://20210512_IBM_SP",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/providers/Microsoft.Authorization/roleDefinitions/18d7d88d-d35e-4fb5-a5c3-7773c20a72d9",
    "roleDefinitionName": "User Access Administrator",
    "scope": "/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]
```
