### ISSUE TITLE
Add support for WebSphere Liberty Operator

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.liberty.aks#65]
- Add a new tab, `Configure operator`, after `Configure application`
- Add param `IBM Supported`: yes/no (default: `no`)
- If `IBM Supported` is yes, display these three **required** params
    - Accept license: checkbox (default:  unchecked)
        - I accept the terms on the license agreement corresponding to the version of IBM Program
in the application container by setting this value to true. See https://ibm.biz/was-license 
for the license agreement applicable to this IBM Program. You must accept the license 
for the installation to work.

    - Edition: drop down with following 3 values (default: none selected)
        - "IBM WebSphere Application Server"
        - "IBM WebSphere Application Server Liberty Core"
        - "IBM WebSphere Application Server Network Deployment"
        - Help text: `Product edition`
    - Product entitlement source: drop down with following 4 values (default: none selected)
        - "Standalone"
        - "IBM WebSphere Hybrid Edition"
        - "IBM Cloud Pak for Applications"
        - "IBM WebSphere Server Family Edition"
       - Help text: `Entitlement source for the product`

Notes: 
- If `IBM Supported` is no, install Open Liberty Operator
- If `IBM Supported` is yes, install WebSphere Liberty Operator
- Use `Edition` and `Product entitlement source` values in app deploy yaml
- App deploy yaml also needs `Metric` parameter. Set it to "Processor Value Unit (PVU)” for "Standalone” and "IBM WebSphere Server Family Edition”, otherwise set it to "Virtual Processor Core (VPC)”.

**Comment by majguo** [comment]
Based on the procedure of deployment, WLO/OLO should be installed before deploying application image. As a result, I think we should add new tab `Configure operator` **before** the existing tab `Configure application`.

**Comment by edburns** [comment]
> Based on the procedure of deployment, WLO/OLO should be installed before deploying application image. As a result, I think we should add new tab Configure operator before the existing tab Configure application.

I agree with @majguo  here.  @git4rk can you please weigh in?

**Comment by gcharters** [comment]
I like the design and agree with `Configure operator` coming before `Configure application`. I think we will need some informational text to explain what "IBM Supported" means.  Must have licenses to cover deployment, blah, blah.

I think we should also install the License Service operator for supported deployments and provide instructions for where to access the information from it.

**Comment by gcharters** [comment]
I’ve thought about this a bit more and think the above approach is not quite right. 

The license information being provided is specific to the container being deployed.  A single operator instance can deploy multiple containers, each under different licenses (e.g. Liberty Core, Liberty Base).

I think we should update the `Configure application` tab to be: `Configure Operator and application` (should Operator be uppercase because it’s a specific thing? :/)

We should add a param at the top: IBM Supported or Trial: yes/no (default: no)

The rest of the proposal remains the same.

Help information for the new param should say: “Choose `yes` if your deployments are to be supported under existing WebSphere entitlements (this includes supported deployments of Open Liberty).  Choose `yes` if you are deploying WebSphere Liberty under the Trial license terms.  Choose `no` if you are deploying Open Liberty unsupported”

**Comment by majguo** [comment]
Thanks @git4rk, @edburns & @gcharters for your comments. 

I created the mockup, and you can preview the UI changes using the **Create UI Definition Sandbox**:
- Open [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade) in a new tab of browser.
- Open UI source code [createUiDefinition.json](https://raw.githubusercontent.com/majguo/azure.liberty.aks/support-wlo/src/main/arm/createUiDefinition.json) in a new tab of the browser.
- Replace the content of work area in **Create UI Definition Sandbox** with the content of **UI source code `createUiDefinition.json`**.
- Click **Preview** at the left-bottom of **Create UI Definition Sandbox**.

Also attached the screenshots for quick overview:

- **IBM supported: No (default)**
  ![image](https://user-images.githubusercontent.com/10357495/197951873-ceeae2f5-ef83-4853-9ccd-088d7d3382b3.png)

- **IBM supported: Yes**
  ![image](https://user-images.githubusercontent.com/10357495/197951651-9f2db353-713b-458c-8905-f825c3df3a39.png)

Please review and respond if you have any comments.

**Comment by gcharters** [comment]
@majguo this looks good to me.

**Comment by majguo** [comment]
Per my testing and [this doc](https://www.ibm.com/docs/en/was-liberty/core?topic=operators-deploying-sample-application), `IBM WebSphere Server Family Edition` should be changed to `IBM WebSphere Application Server Family Edition`.

**Comment by git4rk** [comment]
@gcharters @edburns @majguo Based on our recent experience/discussion (outside of this offering), I think we need to revisit the design:
- License acceptance and entitlement information applies to WebSphere Liberty Application, not to  WLO (WLO is Apache 2.0)
- If customer does not want to deploy an application then we should not require them to accept the license and provide entitlement details.

So, I think, the UI should be like:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/24283162/200195454-7fe69336-b9b8-4b4f-b19e-adef1dc49603.png">
<img width="638" alt="image" src="https://user-images.githubusercontent.com/24283162/200195374-ac946957-bc99-4df2-a29b-d07e92a21975.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/24283162/200195473-116c3367-61e2-4d54-8fc6-f95aca138294.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/24283162/200195403-1e6cbaba-e1aa-49a7-9845-f57cf56c7ba7.png">
