### ISSUE TITLE
Update the version when WLO 1.1.0 is out

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aks#70]
Update the version of WebSphere Liberty Operator when 1.1.0 is out, which is planned for Dec 15, 2022.

**Comment by git4rk** [comment]
@majguo WLO 1.1.0 is published. Can you please verify/update AKS and ARO solutions.

**Comment by majguo** [comment]
@git4rk Sure. I created relative tasks in internal Azure DevOps board this sprint for tracking.

**Comment by majguo** [comment]
Verified that WLO 1.1.0 is automatically installed in `liberty-on-aro` solution:
![image](https://user-images.githubusercontent.com/10357495/209899288-7996e27b-433d-468b-a993-2d68614bcff3.png)
