### ISSUE TITLE
Support auto-scaling for app deployment

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.liberty.aks#99]
The issue is to add auto-scaling support for app deployment in `liberty-on-aks` offer. 

## Mockup design

You can preview the UI design  using the **Create UI Definition Sandbox**:

* Open [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade) in a new tab of browser.
* Open UI source code [createUiDefinition.json](https://raw.githubusercontent.com/majguo/azure.liberty.aks/auto-scaling/src/main/arm/createUiDefinition.json) in a new tab of the browser.
* Replace the content of work area in **Create UI Definition Sandbox** with the content of **UI source code `createUiDefinition.json`**.
* Click **Preview** at the left-bottom of **Create UI Definition Sandbox**.
* Switch to tab **Operator and application** > Select **Yes** for **Deploy an application?** > See UI design details by toggling **Yes**/**No** for section **Auto-scale replicas?**.

Also attached the screenshots for quick overview:

* **Auto-scale replicas? > No (default)**
  ![image](https://github.com/WASdev/azure.liberty.aks/assets/10357495/c320ba29-b407-4551-8a80-d1c54b1b56f1)

- **Auto-scale replicas? > Yes**
  ![image](https://github.com/WASdev/azure.liberty.aks/assets/10357495/aad1fa84-48a7-4699-a0aa-5eea9931d13c)

@edburns @venunathb @git4rk @gcharters Please review and respond if you have any comments, thanks.

**Comment by edburns** [comment]
Reviewed the design with @majguo today. When we have the Liberty Scaling SME, I want to ask this question.

Is the set of options we offer sufficient? There are additional options in the CRD that might make sense:


| label | name|
|------|------|
| resources.limits.cpu | The upper limit of CPU core. Specify integers, fractions (e.g. 0.5), or millicores values(e.g. 100m, where 100m is equivalent to .1 core). |
| resources.limits.memory | The memory upper limit in bytes. Specify integers with suffixes: E, P, T, G, M, K, or power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki.|

**Comment by majguo** [comment]
Updated the UI design per review comments from @gcharters:

![image](https://github.com/WASdev/azure.liberty.aks/assets/10357495/98eda5ee-0885-4511-9e57-3ca87f534dd7)

**Comment by edburns** [comment]
This looks good to me. Please proceed with the implementation.
